version: '3'

networks:
  default:

services:
  golang-order:
    build:
      context: ./golang/OrderService
      dockerfile: Dockerfile
    container_name: order
    ports:
      - 80:8080
    environment: 
      - PRODUCT_SVC_URL=http://golang-product:8080
      - CUSTOMER_SVC_URL=http://golang-customer:8080
      - serviceName=order
      - versionNum=1.0
    networks:
      - default
  golang-customer:
    build:
      context: ./golang/CommonService
      dockerfile: Dockerfile
    container_name: customer
    ports:
      - 8080:8080
    environment: 
      - PRODUCT_SVC_URL=http://golang-product:8080
      - CUSTOMER_SVC_URL=http://golang-customer:8080
      - serviceName=customer
      - versionNum=1.0
    networks:
      - default
  golang-product:
    build:
      context: ./golang/CommonService
      dockerfile: Dockerfile
    container_name: product
    ports:
      - 9090:8080
    environment: 
      - PRODUCT_SVC_URL=http://golang-product:8080
      - CUSTOMER_SVC_URL=http://golang-customer:8080
      - serviceName=product
      - versionNum=1.0
    networks:
      - default


      